name: "${project.name}"
version: "${project.version}"
api: ["1.0.13"]
author: qPexLegendary
description: "Library for easy creating and handling of forms"
main: ru.contentforge.formconstructor.FormConstructor

commands:
  simpleform:
    description: "Test form"
  customform:
    description: "Test form"
  modalform:
    description: "Test form"